// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgl9Tij29Xej1lGJSTR-JUIEAs-rA9I3E',
    appId: '1:293825632708:web:88632e3dbc59aa96b0ac91',
    messagingSenderId: '293825632708',
    projectId: 'getxlern',
    authDomain: 'getxlern.firebaseapp.com',
    storageBucket: 'getxlern.appspot.com',
    measurementId: 'G-ZXJTETZT8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxpPoLgWIdTLNW1HkcQFOndjt8FHaMCBg',
    appId: '1:293825632708:android:df00188cdb9ed526b0ac91',
    messagingSenderId: '293825632708',
    projectId: 'getxlern',
    storageBucket: 'getxlern.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0bUEAG8-fpZOCA6KzI796F_p_dNyCcbc',
    appId: '1:293825632708:ios:f052681fd58126d4b0ac91',
    messagingSenderId: '293825632708',
    projectId: 'getxlern',
    storageBucket: 'getxlern.appspot.com',
    iosBundleId: 'com.example.firebaseGetx',
  );
}
